services:
  redis-master:
    image: redis:7.0
    container_name: redis-master
    command: redis-server --appendonly yes --port 6379
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis-master:/data
    networks:
      redis-cluster:
        ipv4_address: 172.22.0.5

  redis-slave1:
    image: redis:7.0
    container_name: redis-slave1
    command: redis-server --slaveof redis-master 6379 --appendonly yes --port 6379
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis-slave1:/data
    networks:
      - redis-cluster

  redis-slave2:
    image: redis:7.0
    container_name: redis-slave2
    command: redis-server --slaveof redis-master 6379 --appendonly yes --port 6379
    ports:
      - "6381:6379"
    volumes:
      - ./data/redis-slave2:/data
    networks:
      - redis-cluster

  redis-sentinel1:
    image: redis:7.0
    container_name: redis-sentinel1
    command: redis-sentinel /sentinel/sentinel.conf
    ports:
      - "26379:26379"
    volumes:
      - ./redis-sentinel/redis-sentinel.conf:/sentinel/sentinel.conf
    networks:
      - redis-cluster
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2

  redis-sentinel2:
    image: redis:7.0
    container_name: redis-sentinel2
    command: redis-sentinel /sentinel/sentinel.conf
    ports:
      - "26380:26379"
    volumes:
      - ./redis-sentinel/redis-sentinel2.conf:/sentinel/sentinel.conf
    networks:
      - redis-cluster
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2

  redis-sentinel3:
    image: redis:7.0
    container_name: redis-sentinel3
    command: redis-sentinel /sentinel/sentinel.conf
    ports:
      - "26381:26379"
    volumes:
      - ./redis-sentinel/redis-sentinel3.conf:/sentinel/sentinel.conf
    networks:
      - redis-cluster
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2

  php-app:
    image: php:8.1-cli
    container_name: php-app
    volumes:
      - ./php:/var/www/html
    working_dir: /var/www/html
    networks:
      - redis-cluster
    depends_on:
      - redis-sentinel1
      - redis-sentinel2
      - redis-sentinel3
    build:
      context: .
      dockerfile: Dockerfile

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16